### ISSUE TITLE
7.3 beta 4 warning

### ISSUE THREAD

**Issue by JohnRbk** [thii/SwiftHEXColors#27]
7.3 b4 includes some warnings for a deprecated `init:start:end` function.

`let greenHex = hex.substringWithRange(Range<String.Index>(start: hex.startIndex.advancedBy(2), end: hex.startIndex.advancedBy(4)))`

should be changed to:

`let greenHex = hex.substringWithRange(Range<String.Index>(hex.startIndex.advancedBy(2) ..< hex.startIndex.advancedBy(4)))`

**Comment by thii** [comment]
Thanks for reporting. Could you make a patch for that?

**Comment by thii** [comment]
Fixed in #28
