### ISSUE TITLE
Swift 2.3 compatibility

### ISSUE THREAD

**Issue by pablog** [thii/SwiftHEXColors#40]
I've seen there's a branch compatible with Swift 3. Anyway, there's no branch compatible with Swift 2.3, since master is compatible with Swift 2.2.

**Comment by thii** [comment]
Do you really want to use Swift 2.3?

**Comment by kuyazee** [comment]
Me too

**Comment by andwhy** [comment]
+1

**Comment by viktorasl** [comment]
[swift-2.3](/SwiftHEXColors/tree/swift-2.3) is ready to be used.

**Comment by kuyazee** [comment]
Thank you very much
