### ISSUE TITLE
Swift 3 Valid Architectures Fix it !

### ISSUE THREAD

**Issue by YHSX88** [thii/SwiftHEXColors#43]
Hi Just to report that I have brand new project in Xcode 8 and installed the Swift 3 branch
with podfile config

platform :ios, '9.0'
use_frameworks!

target 'SwiftHexColors_SW3' do

pod 'SwiftHEXColors', :git => 'https://github.com/thii/SwiftHEXColors', :branch => 'swift-3.0'

end

And it gave me errors i.e. couldn't compile.
Then I deleted arm7 and arm7s in **Build Settings -> Valid Architectures** 

and then I build again and all was working .

Thank you

**Comment by thii** [comment]
Thank you!
