### ISSUE TITLE
Can return nil?

### ISSUE THREAD

**Issue by MickL** [thii/SwiftHEXColors#44]
Documentation says usage is like:
`let color: UIColor = UIColor(hexString: "#ff8942")`

But how can this work if the function can return nil? Must be `let color: UIColor? = ...` then?

**Comment by thii** [comment]
How about `let color = UIColor(hexString: "#ff8942")`?

**Comment by MickL** [comment]
Anyway documentation needs to be changed.

**Comment by thii** [comment]
Sure.
