### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by 3vangelos** [thii/SwiftHEXColors#56]
Hey there, 

are you guys going to create a new version and add it to the pod spec to reflect the new Swift 4.2. version changes?

Not that big of a deal, but it would kill the SWIFT4.2. warning without having to set the swift version manually in the pod file.

Cheers, 
Evangelos

**Comment by thii** [comment]
The podpec’s Swift version has been updated to 4.2, but for some reason `pod lib lint` is failing so we haven’t been able to publish it yet. In the meantime, you can point your Podfile to this repo’s master to fetch the latest podspec of this library.

**Comment by thii** [comment]
1.2.0 is released.
