### ISSUE TITLE
CFBundleVersion version missing

### ISSUE THREAD

**Issue by Cedrick84** [thii/SwiftHEXColors#60]
CFBundleVersion is missing after building the latest version using carthage.

> "This bundle SwiftHEXColors.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

**Comment by thii** [comment]
I tried with a test project but it didn't seem to be needed.

**Comment by Cedrick84** [comment]
Hi thii, I will play around with it when I have some time. I am working on a project with a very tight deadline now. The project compiles and works fine, but open the plist in the generated framework and look for the `CFBundleVersion` key.  The complaining starts when submitting your app to the Appstore.
